<?php

// 28-11-20255

//create dataase
CREATE DATABASE news_website;

//create users table
CREATE TABLE users(
id INT AUTO_INCREMENT NOT NULL,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
username VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
user_type TINYINT(1) UNSIGNED DEFAULT 1, 
is_active TINYINT(1) DEFAULT 1,    
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,    
PRIMARY KEY (id)
);

//change column name user_type to user_role
ALTER TABLE `users` CHANGE `user_type` `user_role` TINYINT(1) UNSIGNED NULL DEFAULT '1';


//CREATE POSTS TABLE
CREATE TABLE posts(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
title VARCHAR(255) NOT NULL, 
category_id INT UNSIGNED NOT NULL,
post_date DATETIME DEFAULT CURRENT_TIMESTAMP,
author_id INT UNSIGNED NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)   
);

//create category table
CREATE TABLE categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


//alter category table, category post count as defined ALTER TABLE categories
MODIFY posts INT UNSIGNED NOT NULL DEFAULT 0;
