<?php

// 28-11-20255

//create dataase
CREATE DATABASE news_website;

//create users table
CREATE TABLE users(
id INT AUTO_INCREMENT NOT NULL,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
username VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
user_type TINYINT(1) UNSIGNED DEFAULT 1, 
is_active TINYINT(1) DEFAULT 1,    
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,    
PRIMARY KEY (id)
);